spring:
  application:
    name: my-fruit-shop-owner
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/my-fruit
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true